study_support/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root to: "homes#top"
  
  get "homes/top" => "homes#top"
  get "users/my_page" => "users#my_page"
  
  # ゲストユーザー用
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
    get 'users/sign_out' => 'devise/sessions#destroy'
  end
  
  
  resources :tasks, only: [:new, :index, :edit, :update, :create, :destroy] do
    resource :check, only: [:create, :destroy]
  end
  resources :usage_times, only: [:create]
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

study_support/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  
end

study_support/app/models/check.rb
class Check < ApplicationRecord
  belongs_to :user
  belongs_to :task
  
end

study_support/app/models/task.rb
class Task < ApplicationRecord
  has_many :usage_times
  has_many :check, dependent: :destroy
  belongs_to :user
  
  def times_total
    total_times = 0
    usage_times.each do |f|
      total_times += f.elapsed_time
    end
    return total_times
  end
  
  
  
  def check_by?(user)
    check.exists?(user_id: user.id)
  end
  
end

study_support/app/models/usage_time.rb
class UsageTime < ApplicationRecord
  belongs_to :task
  belongs_to :user
  
  
  scope :created_today, -> { where(created_at: Time.zone.now.all_day) } # 今日
  scope :created_yesterday, -> { where(created_at: 1.day.ago.all_day) } # 前日
  scope :created_two_days_ago, -> { where(created_at: 2.day.ago.all_day) } #2日前
  scope :created_three_days_ago, -> { where(created_at: 3.day.ago.all_day) } #3日前
  scope :created_four_days_ago, -> { where(created_at: 4.day.ago.all_day) } #4日前
  scope :created_five_days_ago, -> { where(created_at: 5.day.ago.all_day) } #5日前
  scope :created_six_days_ago, -> { where(created_at: 6.day.ago.all_day) } #6日前
  
end

study_support/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :tasks, dependent: :destroy
  has_many :usage_times, dependent: :destroy
  has_many :check, dependent: :destroy
  
  # 所要時間まとめ
  def total_all(i)
    if i == 1
      a = usage_times.created_today.pluck(:elapsed_time).inject(:+)
    elsif i == 2
      a = usage_times.created_yesterday.pluck(:elapsed_time).inject(:+)
    elsif i == 3
      a = usage_times.created_two_days_ago.pluck(:elapsed_time).inject(:+)
    elsif i == 4
      a = usage_times.created_three_days_ago.pluck(:elapsed_time).inject(:+)
    elsif i == 5
      a = usage_times.created_four_days_ago.pluck(:elapsed_time).inject(:+)
    elsif i == 6
      a = usage_times.created_four_days_ago.pluck(:elapsed_time).inject(:+)
    elsif i == 7
      a = usage_times.created_six_days_ago.pluck(:elapsed_time).inject(:+)
    end
    
    if a.nil?
      0
    else
      (a * 0.01666667).round(2)
    end
  end
  
  
  # ゲストユーザー用
  def self.guest
    find_or_create_by!(name: 'guestuser' ,email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end
  
end

study_support/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def after_sign_in_path_for(resource)
    tasks_path
  end

  def after_sign_out_path_for(resource)
    homes_top_path
  end

  protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

study_support/app/controllers/checks_controller.rb
class ChecksController < ApplicationController
  
  def create 
    @task = Task.find(params[:task_id])
    check = current_user.check.new(task_id: @task.id)
    check.save
    #redirect_to tasks_path(task)
  end
  
  def destroy
    @task = Task.find(params[:task_id])
    check = current_user.check.find_by(task_id: @task.id)
    check.destroy
    #redirect_to tasks_path(task)
  end
  
end

study_support/app/controllers/homes_controller.rb
class HomesController < ApplicationController
  
  def top
    @user = current_user
  end
end

study_support/app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :destroy]
  
  def index
    @user = current_user
    @task = Task.new
    
    #ログインユーザーのタスクを表示させる
    if user_signed_in?
      @tasks = @user.tasks.page(params[:page]).order('updated_at DESC')
    end
    @usage_time = UsageTime.new
  end
  
  def create
    @task = Task.new(task_params)
    @task.user_id = current_user.id
    @task.save
    redirect_to tasks_path, notice: "タスク作成が完了しました。"
  end
  
  def edit
    @user = current_user
    @task = Task.find(params[:id])
  end
  
  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to tasks_path, notice: "タスク編集が完了しました。"
  end
  
  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path, alert: "タスクの削除が完了しました。"
  end
  
  private

  def task_params
    params.require(:task).permit(:title, :body, :start_date, :end_date)
  end
  
  
  # ログインユーザー以外はじく
  def is_matching_login_user
    @task = Task.find(params[:id])
    unless @task.user == current_user
      redirect_to  tasks_path
    end
  end
  
end

study_support/app/controllers/usage_times_controller.rb
class UsageTimesController < ApplicationController
  
  def new
    @usage_time = UsageTime.all
  end
  
  def create
    @usage_time = UsageTime.new(usage_time_params)
    @usage_time.user_id = current_user.id
    @usage_time.save
    redirect_to tasks_path, notice: "時間を記録しました。"
  end
  
  private

  def usage_time_params
    params.require(:usage_time).permit(:task_id, :elapsed_time)
  end
  
end

study_support/app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to tasks_path, notice: 'guestuserでログインしました。'
  end
end

study_support/app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def my_page
    # ユーザー編集追加時以下利用
    @user = current_user
    @times = @user.usage_times
    
    # コンソールチェック用
    # pp @day2
    
  end
  
end

study_support/app/helpers/application_helper.rb
module ApplicationHelper
end

study_support/app/helpers/checks_helper.rb
module ChecksHelper
end

study_support/app/helpers/homes_helper.rb
module HomesHelper
end

study_support/app/helpers/tasks_helper.rb
module TasksHelper
end

study_support/app/helpers/usage_times_helper.rb
module UsageTimesHelper
end

study_support/app/helpers/users_helper.rb
module UsersHelper
end

study_support/app/views/checks/_check.html.erb
<% if task.check_by?(current_user) %>
  <p>
    <%= link_to task_check_path(task), method: :delete, remote: true do %>
      <i class="fa-solid fa-check" style="color: #32CD32;" title="タスク完了済み"></i>
    <%end%>
  </p>
<%else%>
  <p>
    <%= link_to task_check_path(task), method: :post, remote: true do %>
      <i class="fa-solid fa-check" style="color: gray;" title="タスク未完了"></i>
    <%end%>
  </p>
<%end%>

study_support/app/views/checks/create.js.erb
$('#check_<%= @task.id %>').html("<%= j(render 'checks/check', {task: @task}) %>");

study_support/app/views/checks/destroy.js.erb
$('#check_<%= @task.id %>').html("<%= j(render 'checks/check', {task: @task}) %>");

study_support/app/views/homes/my_page.html.erb
<h1>マイページ</h1>

study_support/app/views/homes/top.html.erb
<div class="container">
  <div class="space"></div>
  <div class="row">
    <div class="col">
      <div class="text">STUDY SUPPORT</div>
      
      <div class="text">
        このサイトはポモドーロタイマーを使ったサポートサイトです
      </div>
      
      <div style="margin-top: 10px;"><%= link_to "はじめる", tasks_path, class: "smpleLogin" %></div>
      
      <% if user_signed_in? %>
      <%else%>
        <div><%= link_to 'ゲストログイン（閲覧用）', users_guest_sign_in_path, class: "guestLogin", method: :post %></div>
      <%end%>
        
    </div>
  </div>
</div>

study_support/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StudySupport</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <!--メンターさんが入れたJquery-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/093f51139d.js" crossorigin="anonymous"></script>
    <%= favicon_link_tag('logoFav.ico') %>
  </head>

  <body>
    <header>
      <!--<img src="/assets/logo.jpg" alt="" class="logo1">-->
      <%= image_tag asset_path('logo.jpg'), class: "logo1" %>
      <ul class="navi">
        <%if user_signed_in? %>
          <li><%= link_to homes_top_path, class: "headerTextColor" do %>Top画面<%end%></li>
          <li><%= link_to tasks_path, class: "headerTextColor" do %>ToDoリスト<%end%></li>
          <li data-turbolinks="false"><%= link_to users_my_page_path, class: "headerTextColor" do %>マイページ<%end%></li>
          <li><%= link_to destroy_user_session_path, method: :delete, class: "headerTextColor" do %>ログアウト<%end%></li>
        <%else%>
          <li><%= link_to homes_top_path, class: "headerTextColor" do %>Top画面<%end%></li>
          <li><%= link_to user_session_path, class: "headerTextColor" do %>ログイン<%end%></li>
          <li><%= link_to new_user_registration_path, class: "headerTextColor" do %>アカウント作成<%end%></li>
        <%end%>
        
      </ul>
    </header>
    <main>
      <%= yield %>
    </main>
  </body>
</html>

study_support/app/views/tasks/_check.html.erb
<% if tasks.check_by?(current_user) %>
  <p>
    <%= link_to task_check_path(tasks), method: :delete do %>
      <i class="fa-solid fa-check" style="color: #32CD32;" title="タスク完了済み"></i>
    <%end%>
  </p>
<%else%>
  <p>
    <%= link_to task_check_path(tasks), method: :post do %>
      <i class="fa-solid fa-check" style="color: gray;" title="タスク未完了"></i>
    <%end%>
  </p>
<%end%>

study_support/app/views/tasks/_guestTimer.html.erb
<div class="guestText">アカウントを作成されていないのでToDoリストはご利用できません。</div>
<div class="guestText">
  ポモドーロタイマーのみご使用できます。<br>
  タイマー終了時にアラート音が鳴ります。<br>
</div>
<div id="guestTimerModal">
  <div id="guestTimer">
    <div id="guestMin"></div>
    <span style="font-size: 50px;">:</span>
    <div id="guestSec"></div>
    <div>
      <button id="guestStart">開始</button>
      <button id="guestStop">停止</button>
    </div>
  </div>
</div>

study_support/app/views/tasks/_taskCreation.html.erb
<% if user_signed_in? %>
   <div id="taskCreation">タスク作成</div>
 <%end%>
 <p id="notice"><%= notice %></p>
 <p id="alert"><%= alert %></p>
 <% if user_signed_in? && @user.name == "guestuser" %>
  <div style="text-align: center; margin-bottom: 10px;">
    現在ゲスト用の<span style="color: red;">共有アカウント</span>でログインしています。<br>
    タスク作成時に個人情報などの入力にご注意ください。<br>
  </div>
<%end%>

study_support/app/views/tasks/_taskModal.html.erb
<div id="taskModal">
  <p style="margin: 10px;">タスク作成</p>
  <%= form_with model: task, url: tasks_path , method: :post do |f| %>
    <%= f.text_field :title, placeholder: "タスク名を記入", class: "name", required: true %>
    <%= f.text_area :body, placeholder: "タスク詳細を記入", class: "name" %>
    <div>
      開始日<br>
      <%= f.date_field :start_date,class: "name", min: Date.current %>
    </div>
    <div>
      終了日<br>
      <%= f.date_field :end_date,class: "name", min: Date.current %>
    </div>
    <%= f.submit "作成", class: "submit" %>
  <%end%>
  <button id="taskModalClose" >とじる</button>
</div>

study_support/app/views/tasks/_timer.html.erb
<div id="timerModal">
  <div class="activeTask">作業中のタスク</div>
  <div id="taskTitleShow"></div>
  
  <div id="taskBodyShow"></div>
  
  <div class="timer">
    <div id="min"></div>
    <span style="font-size: 50px;">:</span>
    <div id="sec"></div>
  </div>
  
  <div id="start"><i class="fa-solid fa-play"></i></div>
  <span>　</span>
  <div id="stop"><i class="fa-solid fa-stop"></i></div>
  <div class="confirmation">停止ボタンを押してください</div>
  <div style="color: red; margin-bottom: 10px;">
    ※秒単位は全て切り捨てになります<br>
    ※時間記録の押し忘れに注意してください<br>
    ※ページをリロードするとタイマーがリセットされます
  </div>
  
  <!--時間記録代入用-->
  <%= form_with model: usage_time, url: usage_times_path , method: :post do |f| %>
    <%= f.hidden_field :task_id, :value => 0, id: "idAcquisition" %>
    <%= f.hidden_field :elapsed_time, :value => 0, id: "elapsedTime" %>
    <%= f.submit "時間を記録", class: "timeRecord" %>
  <%end%>
  
  <button id="timerModalClose">とじる</button>
</div>

study_support/app/views/tasks/_timerModal.html.erb
<div class="activeTask">作業中のタスク</div>
<div id="taskTitleShow"></div>

<div id="taskBodyShow"></div>

<div class="timer">
  <div id="min"></div>
  <span style="font-size: 50px;">:</span>
  <div id="sec"></div>
</div>

<!--タイマー再開ボタン-->
<div id="start"><i class="fa-solid fa-play"></i></div>
<span>　</span>
<!--タイマー停止ボタン-->
<div id="stop"><i class="fa-solid fa-stop"></i></div>

<!--以下の機能を使うか検討中...-->
<!--<div class="confirmation">停止ボタンを押してください</div>-->

<div style="color: red; margin: 20px 0;">
  ※タイマー終了時にアラート音が鳴ります。<br>
  ※秒単位は全て切り捨てになります。<br>
  ※作業が終了しましたら時間記録ボタンを押下してください。<br>
  ※ページをリロードするとタイマーがリセットされます。
</div>

<!--時間記録代入用-->
<%= form_with model: usage_time, url: usage_times_path , method: :post do |f| %>
  <%= f.hidden_field :task_id, :value => 0, id: "idAcquisition" %>
  <%= f.hidden_field :elapsed_time, :value => 0, id: "elapsedTime" %>
  <%= f.submit "時間記録", class: "timeRecord" %>
<%end%>

study_support/app/views/tasks/_todoLsit.html.erb
<div class="entireList">
  <div style="margin: 10px;">ToDoリスト</div>
  <% tasks.each do |tasks| %>
    <div class="taskList">
      <div class="taskName">
        タスク名：<br>
        　　詳細：
      </div>
      <div class="taskTitle"><%= tasks.title %></div>
      <div class="taskBody"><%= tasks.body %></div>
      
      <!--時間記録時にID取得に必須-->
      <div class="taskId"><%= tasks.id %></div>
      
      <%= link_to task_path(tasks.id), method: :delete do %><i class="deleteButton fa-solid fa-trash-arrow-up" style="color: black;"></i><%end%>
  
      <div class="btnRightBottom">
        <%= link_to edit_task_path(tasks.id) do %><i class="editButton fa-regular fa-pen-to-square" style="color: black;"></i><%end%>
        
        <!--<%= link_to task_path(tasks.id) do %><i class="showButoon fa-regular fa-calendar-check" style="color: black;"></i><%end%>-->
        
        <i class="timerStart fa-solid fa-play" style="color: black;"></i>
      </div>
    </div>
  <%end%>
</div>

study_support/app/views/tasks/edit.html.erb
<%= form_with model:@task, local:true do |f| %>
<div class="taskTitleEdit">
  <div style="padding-top: 20px;">タイトル</div>
  <%= f.text_field :title, class: "name" %><br>
  <%= f.text_area :body, class: "name" %><br>
  <div>
    開始日<br>
    <%= f.date_field :start_date,class: "name", min: Date.current %>
  </div>
  <div>
    終了日<br>
    <%= f.date_field :end_date,class: "name", min: Date.current %>
  </div>
  
  <%= f.submit "編集を保存", class: "submit", style: "margin-bottom: 30px;" %><br>
  <%= link_to "編集を破棄", tasks_path, class: "submit" %>
</div>
  <!--後に内容や日付変更など追加検討-->
<%end%>

study_support/app/views/tasks/index.html.erb
<!-- 再生プレイヤー -->
<%= audio_tag "jihou1.mp3", controls: true, id: "playAudio" %>

<div id="container">
  
  <!--モーダル出現時の背景-->
  <div id="black"></div>
  
  <!--タスク作成時のモーダル-->
  <%= render 'tasks/taskModal', task: @task %>
  
  <!---ユーザーログイン中かで処理変更-->
  <%= render 'tasks/taskCreation', user: @user %>

  <!--ToDoリスト一覧-->
  <% if user_signed_in? %>
    <div class="entireList">
      <div style="margin: 10px;">ToDoリスト</div>
      <% @tasks.each do |task| %>
        <div class="taskList">
          
          <!--タスク完了チェック-->
          <div id="check_<%= task.id %>">
            <%= render 'checks/check', task: task %>
          </div>
          
          <% if task.start_date.present? && task.end_date.present? %>
            <div class="startDay"><%= task.start_date.strftime("%Y年%m月%d日") %> 開始日</div>
            <div class="endDay"><%= task.end_date.strftime("%Y年%m月%d日") %> 終了日</div>
          <%elsif task.start_date.present? %>
            <div class="startDay"><%= task.start_date.strftime("%Y年%m月%d日") %> 開始日</div>
          <%elsif task.end_date.present? %>
            <div class="endDay"><%= task.end_date.strftime("%Y年%m月%d日") %> 終了日</div>
          <%else%>
            <div class="taskTitle">期日は設定されていません</div>
          <%end%>
          
          <div class="taskTitle">タスク名</div>
          <div class="taskBody"><%= task.title %></div>
          <% if task.body.present? %>
            <div class="taskTitle">詳細</div>
            <div class="taskBody"><%= task.body %></div>
          <%else%>
            <div class="taskTitle">詳細</div>
            <div class="taskBody">記載がありません</div>
          <%end%>
          <!--時間記録時にID取得に必須-->
          <div class="taskId"><%= task.id %></div>
          <%= link_to task_path(task.id), data: {confirm: "削除しますか？"}, method: :delete do %><i class="deleteButton fa-solid fa-trash-arrow-up" style="color: black;" title="タスクを削除する"></i><%end%>
          
          <!--掛かった時間-->
          <span class="taskElapsedTime">タスク経過時刻 <%= task.times_total %>分</span>
          <div class="btnRightBottom">
            <%= link_to edit_task_path(task.id) do %><i class="editButton fa-regular fa-pen-to-square" style="color: black;" title="タスクを編集する"></i><%end%>
            <i class="timerStart fa-solid fa-play" style="color: black;" title="タイマーを開始する"></i>
          </div>
        </div>
      <%end%>
    </div>
  <%else%>
  
    <!--ゲスト用タイマー-->
    <%= render 'tasks/guestTimer' %>
  <%end%>
  
  <!--タイマー用モーダル-->
  <div id="timerModal">
    <%= render 'tasks/timerModal', usage_time: @usage_time %>
  </div>
</div>



<!--kaminari導入-->
<% if @tasks.nil? %>
  
<%else%>
  <%= paginate @tasks %>
<%end%>


<%= javascript_pack_tag 'task/guestIndex'%>
<%= javascript_pack_tag 'task/index'%>

study_support/app/views/tasks/show.html.erb
<h1>タスク詳細一時的に作成</h1>

study_support/app/views/usage_times/new.html.erb
<h1>テスト</h1>

<div>
  <% @usage_time.each do |tasks| %>
    <% if current_user.id == tasks.user_id %>
      <%= tasks.elapsed_time %>
    <%end%>
  <%end%>
</div>


<%= audio_tag "jihou.mp3", controls: true %>

study_support/app/views/users/my_page.html.erb
<div class="myPageBack">
  <div class="myPageChart">
    <!--統計グラフ-->
    <div style="margin: 5px 0;"><%= current_user.name %>さんの</div>
    <div style="margin: 5px 0;">1週間の作業時間</div>
    <canvas id="myChart"></canvas>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script>
      const ctx = document.getElementById('myChart');
      new Chart(ctx, {
        type: 'bar',
        data: {
          labels: ['6日前', '５日前', '４日前', '３日前', '２日前', '1日前', '今日'],
          datasets: [{
            tension: 0.3,
            label: '1週間の作業時間',
            data: [<%= current_user.total_all(7) %>,<%= current_user.total_all(6) %>,<%= current_user.total_all(5) %>,<%= current_user.total_all(4) %>,<%= current_user.total_all(3) %>,<%= current_user.total_all(2) %>,<%= current_user.total_all(1) %>],
            
            //barの色、太さ、線の色
            backgroundColor: [ '#B0E0E6' ],
            borderColor: ['#B0E0E6'],
            borderWidth: 3
          }]
        },
        options: {
          scales: {
            y: {
              beginAtZero: true,
              suggestedMin: 1,
              suggestedMax: 12,
              ticks: {
                // Include a dollar sign in the ticks
                callback: function(value, index, ticks) {
                  return value + "h";
                }
              }
            }
          }
        }
      });
    </script>
    <!--統計グラフ-->
  </div>
</div>

study_support/app/views/users/show.html.erb
<h1>マイページ</h1>
<div><%= @usage_time_yesterday_usage_times %></div>
<div><%= @tasks %></div>
<div class="myPageBack">
  <div class="myPageChart">
    <!--統計グラフ-->
    <div class="text-center">７日間の作業比率</div>
    
      <canvas id="myChart"></canvas>
    
    
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script>
      const ctx = document.getElementById('myChart');
      new Chart(ctx, {
        type: 'bar',
        data: {
          labels: ['6日前', '５日前', '４日前', '３日前', '２日前', '1日前', '今日'],
          datasets: [{
            tension: 0.3,
            label: '1週間の時間',
            data: [1,2,3,4,5,<%= @usage_time_yesterday_usage_times %>, <%= @usage_time_today_usage_times %>,],
            
            //barの色、太さ、線の色
            backgroundColor: [ '#B0E0E6' ],
            borderColor: ['#B0E0E6'],
            borderWidth: 3
          }]
        },
        options: {
          scales: {
            y: {
              beginAtZero: true,
              suggestedMin: 1,
              suggestedMax: 12
            }
          }
        }
      });
    </script>
    <!--統計グラフ-->
  </div>
</div>